version: '3'

services:
  idokep-to-wunderground:
    image: ghcr.io/amargo/idokep-to-wunderground:main
    container_name: idokep-to-wunderground
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Budapest
      - PYTHONIOENCODING=utf-8
