name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * SUN"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Run Renovate
        uses: renovatebot/github-action@04c5c5c6bdc22714621d741d9a81022f702ee797 # v38.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}          
